""" @package carsview
The Django Views module
Provides views for CRUD operations on cars
"""
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import generics
from sungard.models import *
from sungard.serializers import *

import logging
log = logging.getLogger(__name__)


class CarApiListView(generics.ListCreateAPIView):
    ## Used to add a \ref Car object to the databasea(POST) or to retrieve a list of Car objects in database (GET)
    # The relative URL used for this is given by 
    # /rest/sungard/cars 
    # 
    queryset = Car.objects.all()
    serializer_class = CarSerializer
    paginate_by = 10

class CarApiUpdateView(generics.RetrieveUpdateDestroyAPIView):
    ## Used to update a \ref Car object in the database or to retrieve/destroy an individual car object in database. (PUT/DELETE/GET)
    # The relative URL used for this is given by 
    #/rest/sungard/cars/<id> where id is the autogenerated id of the Car object when it is saved to DB.
    queryset = Car.objects.all()
    serializer_class = CarSerializer
    lookup_field = 'id'
